#!/usr/bin/tcsh -f

set macros = ( \
    unit_tests/unit_test_null_macro.C \
    unit_tests/unit_test_load_bfc.C   \
    unit_tests/unit_test_load_agml.C  \
    unit_tests/unit_test_load_y2019a.C \
)

set kumacs = ( \
    unit_tests/unit_test_load_y2019a.kumac \
)

foreach test ( $macros )
  root4star -q -b $test >& root4star-$test:t:r.log
  echo "[$test:t:r] $status"
end



foreach test ( $kumacs )
  starsim -w 0 -q -b $test >& starsim-$test:t:r.log
  echo "[$test:t:r] $status"
end


